const SET_MOVIE = "SET_MOVIE"
const SET_PAGENUM = "SET_PAGENUM"
const SET_PREVPAGE = "SET_PREVPAGE"
const SET_NEXTPAGE = "SET_NEXTPAGE"

export default { SET_MOVIE, SET_PAGENUM,SET_PREVPAGE,SET_NEXTPAGE }